### ISSUE TITLE
Bulk mode not working

### ISSUE THREAD

**Issue by GodHacked** [RasaHQ/paraphraser#11]
Hi, I'm trying to implement bulk mode, however, it doesn't seem to be working and couldn't manage to find out why.

Here are my inputs and logs

Input File: test.csv 
> How can I apply for a new passport?

Command:
`docker run --rm -it -v $PWD/data:/etc/data dakshvar22/paraphraser_cpu:latest --input_file test.csv --output_format csv
  --language en`

Log:
`
2022-01-26 17:34:03.416578: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2022-01-26 17:34:03.416618: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/miniconda3/lib/python3.7/site-packages/gensim/similarities/__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)
| [src] dictionary: 65400 types
| [tgt] dictionary: 65400 types
| loaded 1 examples from: test_bin/test.src-tgt.src
| loaded 1 examples from: test_bin/test.src-tgt.tgt
| test_bin test src-tgt 1 examples
INFO:absl:Using /tmp/tfhub_modules to cache modules.
INFO:absl:Downloading TF-Hub Module 'https://tfhub.dev/google/universal-sentence-encoder-multilingual/3'.
INFO:absl:Downloading https://tfhub.dev/google/universal-sentence-encoder-multilingual/3: 180.01MB
INFO:absl:Downloaded https://tfhub.dev/google/universal-sentence-encoder-multilingual/3, Total size: 266.88MB
INFO:absl:Downloaded TF-Hub Module 'https://tfhub.dev/google/universal-sentence-encoder-multilingual/3'.
2022-01-26 17:34:36.389747: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-01-26 17:34:36.389789: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2022-01-26 17:34:36.389808: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (46bf4c8c385e): /proc/driver/nvidia/version does not exist
2022-01-26 17:34:36.390029: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-26 17:34:36.397253: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3393630000 Hz
2022-01-26 17:34:36.399661: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56030dbe5140 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-01-26 17:34:36.399694: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
| loaded 1 examples from: test_bin/test.src-tgt.src
| loaded 1 examples from: test_bin/test.src-tgt.tgt
| test_bin test src-tgt 1 examples
Traceback (most recent call last):
  File "run_paraphraser.py", line 136, in <module>
    run(args)
  File "run_paraphraser.py", line 68, in run
    run_bulk(model, args)
  File "run_paraphraser.py", line 56, in run_bulk
    write_collection(collection, DATA_PATH, args.output_format)
  File "/home/src/io.py", line 97, in write_collection
    csv_content = serialize_collection_as_csv(collection)
  File "/home/src/io.py", line 86, in serialize_collection_as_csv
    for paraphrase in paraphrases:
TypeError: 'NoneType' object is not iterable
`

Input File: test.yaml
`
nlu:
- intent: ask_query
  examples:
   - How to apply for passport
`

Command:
`
docker run --rm -it -v $PWD/data:/etc/data dakshvar22/paraphraser_cpu:latest --input_file test.yaml --output_format yaml --language en
`
Log:
`
2022-01-26 17:41:56.039870: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2022-01-26 17:41:56.039916: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/miniconda3/lib/python3.7/site-packages/gensim/similarities/__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)
| [src] dictionary: 65400 types
| [tgt] dictionary: 65400 types
| loaded 1 examples from: test_bin/test.src-tgt.src
| loaded 1 examples from: test_bin/test.src-tgt.tgt
| test_bin test src-tgt 1 examples
INFO:absl:Using /tmp/tfhub_modules to cache modules.
INFO:absl:Downloading TF-Hub Module 'https://tfhub.dev/google/universal-sentence-encoder-multilingual/3'.
INFO:absl:Downloading https://tfhub.dev/google/universal-sentence-encoder-multilingual/3: 180.01MB
INFO:absl:Downloaded https://tfhub.dev/google/universal-sentence-encoder-multilingual/3, Total size: 266.88MB
INFO:absl:Downloaded TF-Hub Module 'https://tfhub.dev/google/universal-sentence-encoder-multilingual/3'.
2022-01-26 17:42:28.736793: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-01-26 17:42:28.736833: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2022-01-26 17:42:28.736863: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (4ae9ac981036): /proc/driver/nvidia/version does not exist
2022-01-26 17:42:28.737022: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-26 17:42:28.741762: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3393630000 Hz
2022-01-26 17:42:28.743740: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5605a397f6e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-01-26 17:42:28.743763: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/rasa/shared/utils/validation.py", line 160, in validate_yaml_schema
    c.validate(raise_exception=True)
  File "/root/miniconda3/lib/python3.7/site-packages/pykwalify/core.py", line 167, in validate
    error_msg=u'.\n - '.join(self.validation_errors)))
pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
 - Value '['How to apply for passport']' is not of type 'str'. Path: '/nlu/0/examples'.
 - Value 'How to apply for passport' is not a dict. Value path: '/nlu/0/examples/0'.
 - Key 'intent' was not defined. Path: '/nlu/0'.
 - Value '['How to apply for passport']' is not of type 'str'. Path: '/nlu/0/examples'.
 - Key 'intent' was not defined. Path: '/nlu/0'.
 - Value '['How to apply for passport']' is not of type 'str'. Path: '/nlu/0/examples'.
 - Key 'intent' was not defined. Path: '/nlu/0'.
 - Value '['How to apply for passport']' is not of type 'str'. Path: '/nlu/0/examples'.: Path: '/'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/src/io.py", line 54, in read_collection
    return read_rasa_collection(input_file_path)
  File "/home/src/io.py", line 41, in read_rasa_collection
    data = load_data(file_path)
  File "/root/miniconda3/lib/python3.7/site-packages/rasa/shared/nlu/training_data/loading.py", line 60, in load_data
    data_sets = [_load(f, language) for f in files]
  File "/root/miniconda3/lib/python3.7/site-packages/rasa/shared/nlu/training_data/loading.py", line 60, in <listcomp>
    data_sets = [_load(f, language) for f in files]
  File "/root/miniconda3/lib/python3.7/site-packages/rasa/shared/nlu/training_data/loading.py", line 112, in _load
    return reader.read(filename, language=language, fformat=fformat)
  File "/root/miniconda3/lib/python3.7/site-packages/rasa/shared/nlu/training_data/formats/readerwriter.py", line 33, in read
    return self.reads(rasa.shared.utils.io.read_file(filename), **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/rasa/shared/nlu/training_data/formats/rasa_yaml.py", line 80, in reads
    self.validate(string)
  File "/root/miniconda3/lib/python3.7/site-packages/rasa/shared/nlu/training_data/formats/rasa_yaml.py", line 68, in validate
    raise e
  File "/root/miniconda3/lib/python3.7/site-packages/rasa/shared/nlu/training_data/formats/rasa_yaml.py", line 65, in validate
    validation.validate_yaml_schema(string, NLU_SCHEMA_FILE)
  File "/root/miniconda3/lib/python3.7/site-packages/rasa/shared/utils/validation.py", line 167, in validate_yaml_schema
    content=source_data,
rasa.shared.utils.validation.YamlValidationException: Failed to validate '/etc/data/test.yaml'. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation:
  in /etc/data/test.yaml:4:
      Value '['How to apply for passport']' is not of type 'str'. Path: '/nlu/0/examples'
  in /etc/data/test.yaml:4:
      Value 'How to apply for passport' is not a dict. Value path: '/nlu/0/examples/0'
  in /etc/data/test.yaml:2:
      Key 'intent' was not defined. Path: '/nlu/0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_paraphraser.py", line 136, in <module>
    run(args)
  File "run_paraphraser.py", line 68, in run
    run_bulk(model, args)
  File "run_paraphraser.py", line 37, in run_bulk
    collection = read_collection(DATA_PATH, args.input_file)
  File "/home/src/io.py", line 57, in read_collection
    "Input file not in the supported format. Please refer to the README to check the supported formats."
RuntimeError: Input file not in the supported format. Please refer to the README to check the supported formats.
`

Can anyone help me, I tried everything for hours but still stuck :/ (maybe a bug ?)

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dakshvar22** [comment]
Thanks @GodHacked for reporting this. I'll take a look into it today :)

**Comment by GodHacked** [comment]
Thanks @dakshvar22, will be looking forward to your response

**Comment by dakshvar22** [comment]
Hey, looks like the data format in the example shared on the README was wrong. Sorry about that.

Can you try the same command but replace the content of the file with something like this:

```
nlu:
- intent: ask_language
  examples: |
    - What language do you speak?
    - Do you only handle english?
```

I tried this locally and it works. Let me know if you still face any issues.

**Comment by GodHacked** [comment]
This one seems to be working, do you have any recommended python library to structure this yaml format ? @dakshvar22

**Comment by dakshvar22** [comment]
Do you mean a library that could help you dump serialized data into the required yaml format or do you mean a library that can check whether the file is valid yaml format or not?

**Comment by GodHacked** [comment]
a library to dump a object (for example questions: ["", "", ""]) into a this format

**Comment by dakshvar22** [comment]
you can also use csv format as mentioned [here](https://github.com/RasaHQ/paraphraser#bulk-generation-mode) as the input format if you like

**Comment by GodHacked** [comment]
well I tried with csv either but It wasn't working too. Can you give me a example csv file ?

**Comment by GodHacked** [comment]
and also @dakshvar22 output as csv not working either here's the error log

Traceback (most recent call last):
  File "/home/run_paraphraser.py", line 136, in <module>
    run(args)
  File "/home/run_paraphraser.py", line 68, in run
    run_bulk(model, args)
  File "/home/run_paraphraser.py", line 56, in run_bulk
    write_collection(collection, DATA_PATH, args.output_format)
  File "/home/src/io.py", line 97, in write_collection
    csv_content = serialize_collection_as_csv(collection)
  File "/home/src/io.py", line 86, in serialize_collection_as_csv
    for paraphrase in paraphrases:
TypeError: 'NoneType' object is not iterable

input file is the same as that you provided me and works as expected with yaml output

**Comment by dakshvar22** [comment]
I can check into that a bit later but for now if your csv file is formatted like:

```
how do I apply for a passport?, question
Is a passport needed to travel outside of my country?, question
```

you can use yaml as output format with the command:

```
docker run --rm -it     -v $PWD/data:/etc/data     dakshvar22/paraphraser_cpu:latest     --input_file input.csv     --output_format yaml    --language en
```

**Comment by dakshvar22** [comment]
@GodHacked `csv` as an output format should be fixed with https://github.com/RasaHQ/paraphraser/pull/12 . The PR just got merged. It should take roughly 30 mins to build the docker images and push an updated one. Please make sure to pull the new docker image before trying it out.

You can now specify `csv` as output format with:

```
docker run --rm -it     -v $PWD/data:/etc/data     dakshvar22/paraphraser_cpu:latest     --input_file input.csv     --output_format csv   --language en
```

Lmk if you face any issues. I'll keep the issue open until I receive an ok from you :)

**Comment by kaanrkaan** [comment]
Thanks, I managed with csv input and yaml output so everything is working as expected rn. On the other hand, I have a reccomendation, can you add a output file parameter so we can output a spesific name format, we may input 2 requests at the same time so the option to have a output file would be really good @dakshvar22 . But so far, I appriciate your help, you've been one of the best open-source coder so far 😄

**Comment by dakshvar22** [comment]
The new docker images should be up.

For the other request, could you please open a separate issue, requesting as a feature? I can't commit when I can add it but i'll try my best. :)
