### ISSUE TITLE
Can't run paraphraser in bulk or interactive mode

### ISSUE THREAD

**Issue by federicotdn** [RasaHQ/paraphraser#4]
I've tried running the paraphraser in both modes, but I'm getting the following error:
```
Traceback (most recent call last):
  File "run_paraphraser.py", line 136, in <module>
    run(args)
  File "run_paraphraser.py", line 68, in run
    run_bulk(model, args)
  File "run_paraphraser.py", line 39, in run_bulk
    all_paraphrases = model.generate_paraphrases(
AttributeError: 'NMTParaphraser' object has no attribute 'generate_paraphrases'
```

From running:
```
docker run --rm -it \
>     -v $PWD/run_paraphraser.py:/home/run_paraphraser.py \
>     dakshvar22/paraphraser_cpu:latest \
>     python run_paraphraser.py \
>     --interactive \
>     --language en
```

**Comment by federicotdn** [comment]
@dakshvar22 I deleted the image downloaded locally, and then run:
```
docker run --rm -it \
>     dakshvar22/paraphraser_cpu:latest \
>     --interactive \
>     --language en
```

However, I got the following error:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "--interactive": executable file not found in $PATH: unknown.
```

It might be related to the image's entry point?

I tried running instead:
```
docker run --rm -it \
>     dakshvar22/paraphraser_cpu:latest
```

And then, once inside the container, I ran `python run_paraphraser.py --interactive --language en`. However, I got the same error again:
```
2021-05-03 13:15:22.161433: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-05-03 13:15:22.161483: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
| [src] dictionary: 65400 types
| [tgt] dictionary: 65400 types
| loaded 1 examples from: test_bin/test.src-tgt.src
| loaded 1 examples from: test_bin/test.src-tgt.tgt
| test_bin test src-tgt 1 examples
Enter a sentence to be paraphrased: Hello, I would like to purchase a toaster
Traceback (most recent call last):
  File "run_paraphraser.py", line 136, in <module>
    run(args)
  File "run_paraphraser.py", line 66, in run
    run_interactive(model, args)
  File "run_paraphraser.py", line 23, in run_interactive
    paraphrases = model.generate_paraphrases(
AttributeError: 'NMTParaphraser' object has no attribute 'generate_paraphrases'
```

**Comment by dakshvar22** [comment]
@federicotdn I just ran this locally after deleting the image (you can see that the image is downloaded):

```
(rasa_master) daksh (main) paraphraser $ docker run --rm -it \
> dakshvar22/paraphraser_cpu:latest \
> --interactive \
> --language en
Unable to find image 'dakshvar22/paraphraser_cpu:latest' locally
latest: Pulling from dakshvar22/paraphraser_cpu
345e3491a907: Pull complete
57671312ef6f: Pull complete
5e9250ddb7d0: Pull complete
0ebfab80d990: Pull complete
76bad59340cc: Pull complete
9421e072bfe5: Pull complete
5cd7644590c8: Pull complete
f9e225ad5ad1: Pull complete
57d6116c0fe2: Pull complete
c24286bd1ae7: Pull complete
9cdb94ea2d0a: Pull complete
6422c62ce372: Pull complete
3a522c00d3c7: Pull complete
f7a0b03db663: Pull complete
Digest: sha256:2d208429ae0c36fc54e35ffe0303f30a760e3ac4dbf997dad02e8dba420fb6f6
Status: Downloaded newer image for dakshvar22/paraphraser_cpu:latest
2021-05-03 14:15:46.887511: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-05-03 14:15:46.887641: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/root/miniconda3/lib/python3.7/site-packages/gensim/similarities/__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)
| [src] dictionary: 65400 types
| [tgt] dictionary: 65400 types
| loaded 1 examples from: test_bin/test.src-tgt.src
| loaded 1 examples from: test_bin/test.src-tgt.tgt
| test_bin test src-tgt 1 examples
Enter a sentence to be paraphrased: Hello I am looking for a toaster.
| loaded 1 examples from: test_bin/test.src-tgt.src
| loaded 1 examples from: test_bin/test.src-tgt.tgt
| test_bin test src-tgt 1 examples
1. Hello I am looking for a toaster.
2. "Hello I'm looking for a toaster".
3. Please I am looking for a toaster.
4. "Hello I'm looking for a toast".)"
5. Hail me to a toaster.
6. Hallow I’m looking for a toaster.
7. Salute that I’m looking for a toaster.
8. Here's a toast.
9. Hola is looking for a toaster. ...
10. It looks for an outlet.
Generation completed in 16.362245321273804
```

Not sure what's the problem on your side 😅

**Comment by dakshvar22** [comment]
I don't think the image got deleted at your end. Maybe you had some layers which it skipped downloading (but it would have skipped only if there wasn't a difference in that layer. Weird 😅 )

**Comment by federicotdn** [comment]
Tried again, now it's working for some reason 🤔  (the hash digest hasn't changed between runs). Thanks!
